### ISSUE TITLE
#dev is misleading

### ISSUE THREAD

**Issue by pfefferle** [indieweb/chat.indieweb.org#11]
the `#dev` link in the menu bar is a bit misleading, because the "real" channel name is `#indieweb-dev`

**Comment by aaronpk** [comment]
The channel name this is bridged with in Slack is just `#dev`, so my thought was that by naming it `#dev` on the web interface, it's just the IRC room that's the odd one out. I think that's fine, since as this has evolved, it's become more of a chat application than just a log viewer, and IRC happens to be one of the ways you can join the chat.
