### ISSUE TITLE
Realtime logs always show date in UTC

### ISSUE THREAD

**Issue by aaronpk** [indieweb/chat.indieweb.org#27]
need to adjust the timezone of the displayed date when rendered via the realtime logs

**Comment by sknebel** [comment]
I noticed this again today and just read the code a bit. 

If the server code were to inject current offset of the timezone somewhere in the page, the javascript receiving the realtime updates could update the displayed date from the UTC timestamp in the <time> tags, after including the new log-line. 

Does this sound like a reasonable solution? (I can't promise I'll get around to implementing it before you, but I thought I'd comment since I'd already spent time on looking into it)

**Comment by aaronpk** [comment]
That seems like a reasonable approach. I'm sure there's a good JS library for time manipulation that could do the work after it knows the offset.
